theme: minima
include:
  - assets
  - Readme.md
  - Lisez_moi.md
markdown: kramdown
title: Cognitive-Weaponization-Matrix
description: Some research I’d like to share, because I believe this knowledge should belong to everyone.
url: "https://anadema.github.io/Cognitive-Weaponization-Matrix"
